name: Update Server

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update_server:
    name: Send files to server
    runs-on: ubuntu-latest
    steps:
      - name: scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.KEY }}
          source: "."
          target: "/home/ubuntu/web"